version: '3'
services:
  ytview:
    build:
      context: .
    logging:
      options:
        max-size: '10m'
        max-file: '7'
    restart: unless-stopped
    volumes:
      - ${PWD}/urls.txt:/app/urls.txt
